<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ButlerSDK_Provider.Gemini.Vertex</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ButlerSDK.Core.Abstractions\ButlerSDK.Core.Abstractions.csproj" />
    <ProjectReference Include="..\ButlerSDK.Provider.Gemini\ButlerSDK.Provider.Gemini.csproj" />
  </ItemGroup>

</Project>
