<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <IsPackable>false</IsPackable>
	  <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Components\ApiKeyHandling\ButlerSDK.ApiKeyMgr\ButlerSDK.ApiKeyMgr.csproj" />
    <ProjectReference Include="..\..\Components\ButlerSDK.ChatController\ButlerSDK.ChatController.csproj" />
    <ProjectReference Include="..\..\Components\ButlerSDK.Core\ButlerSDK.Core.csproj" />
    <ProjectReference Include="..\..\Components\Tools\ButlerSDK.Tools.VirtualTool\ButlerSDK.Tools.VirtualTool.csproj" />
  </ItemGroup>

</Project>
