<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApiKeyMgr\ButlerSDK.ApiKeyMgr.csproj" />
    <ProjectReference Include="..\ApiKeyVaultCreation\ApiKeyVaultCreation.csproj" />
    <ProjectReference Include="..\ApiRateLimiter\ButlerSDK.ApiRateLimiter.csproj" />
    <ProjectReference Include="..\BasicToolStarterClass\ButlerSDK.Tools.ButlerToolBase.csproj" />
    <ProjectReference Include="..\Butler5ProviderGemini\ButlerSDK.Provider.Gemini.csproj" />
    <ProjectReference Include="..\Butler5ProviderOllama\ButlerSDK.Provider.OpenAI.Ollama.csproj" />
    <ProjectReference Include="..\Butler5ProviderOpenAI\ButlerSDK.Provider.OpenAI.csproj" />
    <ProjectReference Include="..\ButlerBaseInternal\ButlerSDK.ChatController.csproj" />
    <ProjectReference Include="..\ButlerSDK.ChatCollections\ButlerSDK.ChatCollections.csproj" />
    <ProjectReference Include="..\ButlerSDK.Tools.AzureMaps\ButlerSDK.Tools.AzureMaps.csproj" />
    <ProjectReference Include="..\ButlerSDK.Tools.Resolver\ButlerSDK.Tools.Resolver.csproj" />
    <ProjectReference Include="..\ButlerSystemToolBase\ButlerSDK.Tools.ButlerSystemToolBase.csproj" />
    <ProjectReference Include="..\ButlerToolBench\ButlerSDK.Tools.Bench.csproj" />
    <ProjectReference Include="..\CommonProtocol\ButlerSDK.Core.Abstractions.csproj" />
    <ProjectReference Include="..\DiscovererTool\ButlerSDK.Tools.DiscovererTool.csproj" />
    <ProjectReference Include="..\ExternProcessLauncher\ButlerSDK.Tools.ExternProcessLauncher.csproj" />
    <ProjectReference Include="..\ExternProcessNetworkToolsWindows\ButlerSDK.Tools.ExternProcessLauncher.Network.Windows.csproj" />
    <ProjectReference Include="..\NonExtNetworkTools\ButlerSDK.Tools.Network.csproj" />
    <ProjectReference Include="..\ProjectDependants\JerryChatbox\ButlerSDK.Core.csproj" />
    <ProjectReference Include="..\SecureStringHelper\ButlerSDK.SecureStringHelper.csproj" />
    <ProjectReference Include="..\ToolSurface\ButlerSDK.Tools.ToolSurface.csproj" />
    <ProjectReference Include="..\VirtualTool\ButlerSDK.Tools.VirtualTool.csproj" />
    <ProjectReference Include="..\WindowsKeyMgr\ButlerSDK.ApiKeyMgr.WindowsKeyMgr.csproj" />
  </ItemGroup>

</Project>
