<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <IsPackable>true</IsPackable>
	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\ApiKeyHandling\ButlerSDK.ApiKeyMgr\ButlerSDK.ApiKeyMgr.csproj" />
		<ProjectReference Include="..\..\ButlerSDK.ChatController\ButlerSDK.ChatController.csproj" />
		<ProjectReference Include="..\..\ButlerSDK.Core.Abstractions\ButlerSDK.Core.Abstractions.csproj" />
		<ProjectReference Include="..\..\ButlerSDK.Tools.ButlerToolBase\ButlerSDK.Tools.ButlerToolBase.csproj" />
		<ProjectReference Include="..\ButlerSDK.Tools.ButlerSystemToolBase\ButlerSDK.Tools.ButlerSystemToolBase.csproj" />
	</ItemGroup>



</Project>
